name: offtk-examples
channels:
  - conda-forge
  - openeye
dependencies:
  - rdkit
  - ambertools
  - openeye-toolkits
  # These dependencies are in addition to the toolkit itself
  - nglview
  - notebook
  - gromacs >=2021=nompi*
  - qcelemental
  - qcportal
  - qcengine
  - pytest
  - nbval
  # https://github.com/openforcefield/openff-toolkit/pull/1232#issuecomment-1080889858
  # openmmforcefields
  # Dependencies of the full Interchange package not included in openff-interchange-base
  - pandas
  - panedr
  # Add back when LAMMPS export is better
  # lammps
